language: python
python:
  - "2.6"
  - "2.7"
install:
  - python bootstrap.py -c ./.travis.cfg
before_script:
  - ln -s ./profiles/base.cfg base.cfg
  - ln -s ./profiles/plone.cfg plone.cfg
script:
  - bin/buildout -c base.cfg
  - bin/buildout -c plone.cfg
