language: python
python:
  - "2.6"
  - "2.7"
install:
  - python bootstrap.py -c ./.travis.cfg
before_script:
  - ln -s ./config/base.cfg base.cfg
  - ln -s ./config/plone-example.cfg plone.cfg
script:
  - bin/buildout -c base.cfg
  - bin/buildout -c plone.cfg
